# https://taskfile.dev

version: "3"

tasks:
  codegen:
    desc: Generate the utilities code
    cmds:
      - chmod +x codegen.ts
      - ./codegen.ts

  test:
    desc: Run all the project tests
    cmd: go test ./...

  lint:
    desc: Run all the project linters
    cmd: golangci-lint run ./...

  fmt:
    desc: Run all the project formatters
    cmd: go fmt ./...
